server:
  port: 80

spring:
  application:
    name: cloud-order-service
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka/,http://localhost:7002/eureka/
      defaultZone: http://127.0.0.1:7001/eureka/