server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 49.233.37.23
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}