server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  sleuth:
    sampler:
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://49.233.37.23:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.example.cloud.entities    # 所有Entity别名类所在包

eureka:
  instance:
    hostname: localhost
    instance-id: payment8001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka/,http://localhost:7002/eureka/
      defaultZone: http://127.0.0.1:7001/eureka
